/**
 * GENERATED by packages/content/scripts/generate-docs.mjs — do not edit by hand.
 * Run `pnpm docs:generate` to refresh. Source of truth: the repo's docs/*.md.
 *
 * The mock loader can't scan disk (it must work in the browser / edge runtime),
 * so generated docs fixtures are surfaced as static imports here and spread into
 * the loader's fixture set.
 */

import docsCommandsHero from '../../fixtures/base-site/components/docs/commands-hero.json' with { type: 'json' }
import docsCommandsMarkdown from '../../fixtures/base-site/components/docs/commands-markdown.json' with { type: 'json' }
import docsDeployingHero from '../../fixtures/base-site/components/docs/deploying-hero.json' with { type: 'json' }
import docsDeployingMarkdown from '../../fixtures/base-site/components/docs/deploying-markdown.json' with { type: 'json' }
import docsEditorSetupHero from '../../fixtures/base-site/components/docs/editor-setup-hero.json' with { type: 'json' }
import docsEditorSetupMarkdown from '../../fixtures/base-site/components/docs/editor-setup-markdown.json' with { type: 'json' }
import docsGettingStartedHero from '../../fixtures/base-site/components/docs/getting-started-hero.json' with { type: 'json' }
import docsGettingStartedMarkdown from '../../fixtures/base-site/components/docs/getting-started-markdown.json' with { type: 'json' }
import docsRunbooksHubSetupHero from '../../fixtures/base-site/components/docs/runbooks/hub-setup-hero.json' with { type: 'json' }
import docsRunbooksHubSetupMarkdown from '../../fixtures/base-site/components/docs/runbooks/hub-setup-markdown.json' with { type: 'json' }
import docsStorybookHero from '../../fixtures/base-site/components/docs/storybook-hero.json' with { type: 'json' }
import docsStorybookMarkdown from '../../fixtures/base-site/components/docs/storybook-markdown.json' with { type: 'json' }
import docsThemingHero from '../../fixtures/base-site/components/docs/theming-hero.json' with { type: 'json' }
import docsThemingMarkdown from '../../fixtures/base-site/components/docs/theming-markdown.json' with { type: 'json' }
import docsTroubleshootingHero from '../../fixtures/base-site/components/docs/troubleshooting-hero.json' with { type: 'json' }
import docsTroubleshootingMarkdown from '../../fixtures/base-site/components/docs/troubleshooting-markdown.json' with { type: 'json' }
import docsWorkingWithAHubHero from '../../fixtures/base-site/components/docs/working-with-a-hub-hero.json' with { type: 'json' }
import docsWorkingWithAHubMarkdown from '../../fixtures/base-site/components/docs/working-with-a-hub-markdown.json' with { type: 'json' }
import docsCommandsPage from '../../fixtures/base-site/pages/docs/commands.json' with { type: 'json' }
import docsDeployingPage from '../../fixtures/base-site/pages/docs/deploying.json' with { type: 'json' }
import docsEditorSetupPage from '../../fixtures/base-site/pages/docs/editor-setup.json' with { type: 'json' }
import docsGettingStartedPage from '../../fixtures/base-site/pages/docs/getting-started.json' with { type: 'json' }
import docsRunbooksHubSetupPage from '../../fixtures/base-site/pages/docs/runbooks/hub-setup.json' with { type: 'json' }
import docsStorybookPage from '../../fixtures/base-site/pages/docs/storybook.json' with { type: 'json' }
import docsThemingPage from '../../fixtures/base-site/pages/docs/theming.json' with { type: 'json' }
import docsTroubleshootingPage from '../../fixtures/base-site/pages/docs/troubleshooting.json' with { type: 'json' }
import docsWorkingWithAHubPage from '../../fixtures/base-site/pages/docs/working-with-a-hub.json' with { type: 'json' }
import docsCommandsSlot from '../../fixtures/base-site/slots/docs/commands-main.json' with { type: 'json' }
import docsDeployingSlot from '../../fixtures/base-site/slots/docs/deploying-main.json' with { type: 'json' }
import docsEditorSetupSlot from '../../fixtures/base-site/slots/docs/editor-setup-main.json' with { type: 'json' }
import docsGettingStartedSlot from '../../fixtures/base-site/slots/docs/getting-started-main.json' with { type: 'json' }
import docsRunbooksHubSetupSlot from '../../fixtures/base-site/slots/docs/runbooks/hub-setup-main.json' with { type: 'json' }
import docsStorybookSlot from '../../fixtures/base-site/slots/docs/storybook-main.json' with { type: 'json' }
import docsThemingSlot from '../../fixtures/base-site/slots/docs/theming-main.json' with { type: 'json' }
import docsTroubleshootingSlot from '../../fixtures/base-site/slots/docs/troubleshooting-main.json' with { type: 'json' }
import docsWorkingWithAHubSlot from '../../fixtures/base-site/slots/docs/working-with-a-hub-main.json' with { type: 'json' }
import type { EnrichedContentItem } from '../types'

export const docsFixtures = [
  docsCommandsHero,
  docsCommandsMarkdown,
  docsCommandsSlot,
  docsCommandsPage,
  docsDeployingHero,
  docsDeployingMarkdown,
  docsDeployingSlot,
  docsDeployingPage,
  docsEditorSetupHero,
  docsEditorSetupMarkdown,
  docsEditorSetupSlot,
  docsEditorSetupPage,
  docsGettingStartedHero,
  docsGettingStartedMarkdown,
  docsGettingStartedSlot,
  docsGettingStartedPage,
  docsRunbooksHubSetupHero,
  docsRunbooksHubSetupMarkdown,
  docsRunbooksHubSetupSlot,
  docsRunbooksHubSetupPage,
  docsStorybookHero,
  docsStorybookMarkdown,
  docsStorybookSlot,
  docsStorybookPage,
  docsThemingHero,
  docsThemingMarkdown,
  docsThemingSlot,
  docsThemingPage,
  docsTroubleshootingHero,
  docsTroubleshootingMarkdown,
  docsTroubleshootingSlot,
  docsTroubleshootingPage,
  docsWorkingWithAHubHero,
  docsWorkingWithAHubMarkdown,
  docsWorkingWithAHubSlot,
  docsWorkingWithAHubPage,
] as unknown as EnrichedContentItem[]
