/**
 * GENERATED by packages/content/scripts/generate-docs.mjs — do not edit by hand.
 * Run `pnpm docs:generate` to refresh. Source of truth: the repo's docs/*.md.
 *
 * The mock loader can't scan disk (it must work in the browser / edge runtime),
 * so generated docs fixtures are surfaced as static imports here and spread into
 * the loader's fixture set.
 */

import docsHero from '../../fixtures/base-site/components/docs-hero.json' with { type: 'json' }
import docsMarkdown from '../../fixtures/base-site/components/docs-markdown.json' with { type: 'json' }
import docsEditorSetupHero from '../../fixtures/base-site/components/docs/editor-setup-hero.json' with { type: 'json' }
import docsEditorSetupMarkdown from '../../fixtures/base-site/components/docs/editor-setup-markdown.json' with { type: 'json' }
import docsRunbooksHubSetupHero from '../../fixtures/base-site/components/docs/runbooks/hub-setup-hero.json' with { type: 'json' }
import docsRunbooksHubSetupMarkdown from '../../fixtures/base-site/components/docs/runbooks/hub-setup-markdown.json' with { type: 'json' }
import docsPage from '../../fixtures/base-site/pages/docs.json' with { type: 'json' }
import docsEditorSetupPage from '../../fixtures/base-site/pages/docs/editor-setup.json' with { type: 'json' }
import docsRunbooksHubSetupPage from '../../fixtures/base-site/pages/docs/runbooks/hub-setup.json' with { type: 'json' }
import docsSlot from '../../fixtures/base-site/slots/docs-main.json' with { type: 'json' }
import docsEditorSetupSlot from '../../fixtures/base-site/slots/docs/editor-setup-main.json' with { type: 'json' }
import docsRunbooksHubSetupSlot from '../../fixtures/base-site/slots/docs/runbooks/hub-setup-main.json' with { type: 'json' }
import type { EnrichedContentItem } from '../types'

export const docsFixtures = [
  docsEditorSetupHero,
  docsEditorSetupMarkdown,
  docsEditorSetupSlot,
  docsEditorSetupPage,
  docsHero,
  docsMarkdown,
  docsSlot,
  docsPage,
  docsRunbooksHubSetupHero,
  docsRunbooksHubSetupMarkdown,
  docsRunbooksHubSetupSlot,
  docsRunbooksHubSetupPage,
] as unknown as EnrichedContentItem[]
